### ISSUE TITLE
clapack: ?trexc use wrong type for compq

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/lapack#160]
`genLapack.pl` gives `comp?` named variables always the type `lapack.CompSV`. `?trexc` routines are not related to SVD, so a better type would be `lapack.EigComp`.

**Comment by kortschak** [comment]
Would `lapack.Comp` suffice? It would be much simpler to make that change safely than to try to differentiate all the ED and SVD uses.

**Comment by vladimir-ch** [comment]
I think that `lapack.Comp` is a good solution. Also, we should review all the byte types and consts in lapack before the stability promise.

**Comment by btracey** [comment]
File a reminder issue?

**Comment by vladimir-ch** [comment]
Resolved by #174
