### ISSUE TITLE
lapacke: Dgeev discards necessary information by returning bool instead of int

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/lapack#187]

**Comment by kortschak** [comment]
Do *geevx also want this change?

**Comment by vladimir-ch** [comment]
I think so. I would like to have Dgeevx eventually, it doesn't require adding that many new routines but provides much more information/value for the effort already invested. So I vote for adding Dgeev first, so that the matrix package can move forward, and later add Dgeevx and interface it from matrix.

**Comment by kortschak** [comment]
OK. Done
