### ISSUE TITLE
native: Dlaswp panics when incX != 1 and -1

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/lapack#205]
Reference LAPACK allows any value of INCX.

**Comment by vladimir-ch** [comment]
While it is true that the reference implementation allows any INCX, it does not seem beneficial and reasonable to do so (I think this is what led @btracey do disallow other values that 1 and -1). I could even imagine departing here from the reference and hope that they eventually do the same. For some background see https://github.com/Reference-LAPACK/lapack/issues/92 and https://github.com/Reference-LAPACK/lapack/commit/2ceda6db0f046b1b676030f9b6d92541e6222e3c

**Comment by btracey** [comment]
If `|incx| != 1` there is no way to satisfy the behavior of the method.

It's unclear to me how much we want to conform to the "spec" and how much we want to prevent bad ideas.

**Comment by vladimir-ch** [comment]
> If |incx| != 1 there is no way to satisfy the behavior of the method.

Recently I submitted a patch to Reference LAPACK to fix a bug in DLASWP and they also updated the docs. I think it is possible to satisfy the described behavior but it really does not make much sense to have `|incX| != 1`. I did implement it but then when writing a test for it, I gave up, so much effort and it is simply not worth it.

To sum it up, I would vote in this case to prevent bad ideas and not conform to the "spec", and close this issue.

**Comment by kortschak** [comment]
I also vote for not following the current LAPACK reference in this case. From what @langou wrote in the commit, there is every possibility that the behaviour will change to forbid non-unit increments. We don't need to add to any inertia that slows that change.

**Comment by vladimir-ch** [comment]
Thanks for the input.
