### ISSUE TITLE
cgo: tests for Dormbr and Dormlq comments though fixes in OpenBLAS merged

### ISSUE THREAD

**Issue by kortschak** [gonum/lapack#241]
This is a complicated issue. The tests for Dormbr and Dormlq are commented out with reference to OpenBLAS issues and PRs. The issues have been closed and the PRs have been merged. This would suggest that these tests could and should be uncommented. I have just tried that, and they fail.

```
$ CGO_LDFLAGS="-L/usr/local -lopenblas" go test -run Dormlq
*** Error in `/tmp/go-build141511666/github.com/gonum/lapack/cgo/_test/cgo.test': free(): invalid next size (fast): 0x00000000028bb7b0 ***
[more]
```
```
$ CGO_LDFLAGS="-L/usr/local -lopenblas" go test -run Dormbr
 ** On entry to DORMBRP parameter number 13 had an illegal value
[more]
```

**Comment by vladimir-ch** [comment]
I quickly checked and the transposes in both `lapacke_dormbr_work` and `lapacke_dormlq_work` are not being done correctly. I will submit issues to the reference.

**Comment by vladimir-ch** [comment]
Submitted:
https://github.com/Reference-LAPACK/lapack/issues/121
https://github.com/Reference-LAPACK/lapack/issues/122
