### ISSUE TITLE
main.go example

### ISSUE THREAD

**Issue by davmaz** [gonum/lapack#89]
Sorry if I'm out of place here, but can you refer me to a simple "main.go" that uses the lapack package you've contributed? It's really enticing, but I don't have anywhere to start (in go).

**Comment by kortschak** [comment]
The main use of lapack packages is in gonum/matrix. You would probably benefit from reading code that uses lapack calls there. Otherwise, the calls are just Go-idiomatised versions of the LAPACK functions, and reading the documentation and associated material for that suite would be helpful.

**Comment by btracey** [comment]
To expand on @kortschak's point a bit, you should first see if mat64 solves your problem. The functions in lapack are either used directly (in a nicer form) by mat64, or are sub functions needed for the implementation of the main functions. There are some functions that are useful directly and are not supported ideally by mat64 (for example, computing the eigenvalues of a matrix that is specifically symmetric tridiagonal). In those cases you can call lapack today, but also submit a feature request issue in matrix. 

If you're just interested in learning how the specific algorithms work, then as @kortschak suggested you should start with the mat64 code, as in the LU type, for example.

**Comment by davmaz** [comment]
Thank you very much for the pointers. I'm left with 2 questions though:
1) I tried the code in mat64 shown here:https://godoc.org/github.com/gonum/matrix/mat64#example-Cholesky
the 'play' option shows a full main.go to work with. AND, I'm particularly interested in Cholesky decomposition. But I get errors when building like this:
# github.com/gonum/matrix/mat64
../../github.com/gonum/matrix/mat64/svd.go:96: undefined: lapack64.Gesvd
../../github.com/gonum/matrix/mat64/svd.go:98: undefined: lapack64.Gesvd
../../github.com/gonum/matrix/mat64/vector.go:134: undefined: asm.DscalIncTo
../../github.com/gonum/matrix/mat64/vector.go:142: undefined: asm.DscalInc

2) I don't know how to use the "Use" method to select the C optimized versions mentioned in the docs. Might you point me to a simple example or a description of how to use Use?

Also, at some point after I've learned enough, I'd love to contribute to your work.
Thanks!

**Comment by btracey** [comment]
We just added dgesvd to lapack. I would guess that you need to update.

go get -u -t github.com/gonum/matrix/mat64

**Comment by davmaz** [comment]
I found out the answer to #2 above (in your code)!
// Copyright ©2015 The gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//+build cblas

package mat64

import (
	"github.com/gonum/blas/blas64"
	"github.com/gonum/blas/cgo"
)

func init() {
	blas64.Use(cgo.Implementation{})
}

so I know how to do that now...

**Comment by davmaz** [comment]
Thanks for the update to lapack above! Cholesky now works! Beautiful.
I may have been premature in my enthusiasm regarding the Use function. It looks like that's part of the package. I'm still unclear on how to use the cgo OpenBLAS functionality. Might you enlighten me?

**Comment by jonlawlor** [comment]
OpenBLAS is an implementation of the [BLAS](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms) that provides better performance than the native go implementation.  If you're just exploring the gonum packages, I recommend using the native go implementation.  The performance will be worse, but if it becomes an issue you can swap out the back end BLAS library, which is kind of the point of the .Use function.

**Comment by btracey** [comment]
I don't understand your question @davmaz . If that code compiled for you (and you have CGO_LDFLAGS set), then you are using the cgo functionality.

**Comment by davmaz** [comment]
Yes, you're right. It's working well. Thanks for the guidance.

**Comment by kortschak** [comment]
Is this resolved?

**Comment by davmaz** [comment]
Dan,
  Yes, it's resolved.

Thanks,
Dave
________________________________
