### ISSUE TITLE
doc: harmonise use of matrix bracket characters

### ISSUE THREAD

**Issue by kortschak** [gonum/lapack#97]
In some places '(' and ')' are used, while in others '[' and ']' are used. We should be consistent, but a choice needs to be made first.

**Comment by vladimir-ch** [comment]
From my student years I am used to parenthesis for denoting matrices, but since our gopher logo uses square brackets, the choice seems to be clear :-)

**Comment by btracey** [comment]
Brackets are nobody's favorite but they are everybody's favorite.
